/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JUMBO COMPUTERS
 */
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
public class international extends javax.swing.JFrame {

    /**
     * Creates new form international
     */
    public international() {
        initComponents();
        getContentPane().setBackground(new Color(0, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton3);
        buttonGroup1.add(jRadioButton6);

        buttonGroup2.add(jRadioButton9);
        buttonGroup2.add(jRadioButton8);

        buttonGroup3.add(jRadioButton5);
        buttonGroup3.add(jRadioButton7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JINNAH INTERNATIONAL AIRPORT , KARACHI\t", "ALLAMA IQBAL INTERNATIONAL AIRPORT , LAHORE", "MULTAN INTERNATIONAL AIRPORT , MULTAN", "BACHA KHAN INTERNATIONAL AIRPORT ,PESHAWAR", "FAISLABAD INTERNATIONAL AIRPORT , FAISLABAD", "QUEETA INTERNATIONAL AIRPORT, QUEETA", "GAWADAR INTERNATIONAL AIRPORT , GAWADAR", "ISLAMABAD INTERNATIONAL AIRPORT , ISLAMBAD", " ", " ", " ", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 204, 204));
        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel9.setText("INTERNATIONAL FLIGHT");

        jLabel3.setBackground(java.awt.Color.orange);
        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel3.setText("DESTINATION");

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DESTINATION", "DUBAI INTERNATIONAL AIRPORT,DUBAI", "FRANKFURT AIRPORT,GERMANY", "MADRID BARAJAS AIRPORT ,SPAIN", "AMSTERDAM AIRPORT SCHIPHOLl ,NETHERLANDS" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(java.awt.Color.orange);
        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel8.setText("FROM");

        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton6.setText("ECONOMY");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton3.setText("FIRST CLASS");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton1.setText("BUSINESS");

        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton5.setText("ONEWAY");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton7.setText("RETUN TICKET");

        jRadioButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton8.setText("CHILD");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jRadioButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton9.setText("ADULT");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("TOTAL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("TAX");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("SUB-TOTAL");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("TOTAL");
        jButton1.setToolTipText("TOTAL COST OF TICKETS");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXIT");
        jButton2.setToolTipText("CLOSE WINDOW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("RESET");
        jButton3.setToolTipText("RESET EVERYTING");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("PAYMENT");
        jButton4.setToolTipText("PAYMENT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CLASS");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TICKET");

        jTextField8.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("CHILD");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("ADULT");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("FROM");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("DESTINATION");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("TIME");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("ROUTE");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("DATE");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("PRICE");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("TICKET NUMBER");

        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                                    .addComponent(jTextField9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField14)
                            .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 176, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(375, 375, 375))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 23, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jRadioButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton7)
                                    .addComponent(jRadioButton8)
                                    .addComponent(jRadioButton3))))
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
       
       
        JOptionPane.showMessageDialog(null,"do you want to exit?");
            try{

                System.exit(0);

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"error");
            } 
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
       jTextField6.setText("");
       jTextField7.setText("");
       jTextField5.setText("");
       jTextField8.setText("");
       jTextField13.setText("");
       jTextField9.setText("");
       jTextField14.setText("");
       jTextField10.setText("");
       jTextField11.setText("");
       jTextField12.setText("");
       jRadioButton1.setSelected(false);
       jRadioButton9.setSelected(false);
       jRadioButton7.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton8.setSelected(false);
       jRadioButton5.setSelected(false);
       jRadioButton6.setSelected(false);
       jComboBox4.setSelectedItem("DESTINATION");    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
          new CustomerInfo().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //TIME
       Calendar timer =Calendar.getInstance();
       timer.getTime();
       SimpleDateFormat tTime = new SimpleDateFormat("HH:MM:ss");
       jTextField11.setText(tTime.format(timer.getTime()));
       
       //DATEE
       SimpleDateFormat tdate=new SimpleDateFormat("dd-MMM-YYYY");
       jTextField10.setText(tdate.format(timer.getTime()));
       
       jTextField8.setText((String) jComboBox1.getSelectedItem()+"*");
       jTextField9.setText((String) jComboBox4.getSelectedItem()+"*");
       
       //number
       
       int num1;
       String q1="";
       num1 = 1234+(int)(Math.random()*6756);
       q1+= num1 +12345;
       jTextField13.setText(q1);
       
       jTextField12.setText("ANY");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        double tax =100;
        double L1=2000;
        double L2=4000;
        double L3=6000;
        double L4=1200;
        double totalcost,eco=700,fclass=1000,bclass=1500;
        
        if((jRadioButton6.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L1)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton6.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*(L1*2))/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
       else if((jRadioButton6.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*(L1*2))/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
       else if((jRadioButton6.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*(L1*2))/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
       else if((jRadioButton6.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton5.isSelected()))
        {
            totalcost=(tax*L1)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONEWAY");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
       else if((jRadioButton6.isSelected())&&(jRadioButton9.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*(L1*2))/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        //------------------------------------------------------------------------------------------------
        
      else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L1)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
      else if((jRadioButton3.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton5.isSelected()))
        {
            totalcost=(tax*L1)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
       else if((jRadioButton3.isSelected())&&(jRadioButton7.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*(L1*2))/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*(L1*2))/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
       else if((jRadioButton3.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L1)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
       else if((jRadioButton3.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L1)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("ONE");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
         //------------------------------------------------------------------------------------------------
       else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L1)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("BUSINESS");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
       else if((jRadioButton1.isSelected())&&(jRadioButton9.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L1)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("BUSINESS");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
       else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton8.isSelected()))
        {
            totalcost=(tax*L1)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("BUSINESS");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L1)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("BUSINESS");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
       else if((jRadioButton1.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L1)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("BUSINESS");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
       else if((jRadioButton1.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L1)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L1);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONE");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
        //-------------------------------------------------------NEW LOACTION-----------------------------------------------------------------
        
        
       else if((jRadioButton6.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
         else if((jRadioButton6.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton6.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        else if((jRadioButton6.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        else if((jRadioButton6.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton5.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONEWAY");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
        else if((jRadioButton6.isSelected())&&(jRadioButton9.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        //------------------------------------------------------------------------------------------------
        
       else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
       else if((jRadioButton3.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton5.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        else if((jRadioButton3.isSelected())&&(jRadioButton7.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
         else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton3.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
        else if((jRadioButton3.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONE");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
         //------------------------------------------------------------------------------------------------
        else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton1.isSelected())&&(jRadioButton9.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton8.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
         else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton1.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
        else if((jRadioButton1.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L2)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L2);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L2+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONE");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
        //------------------------------------------------------NEW LOCATION---------------------------------------
        
         
       else if((jRadioButton6.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
         else if((jRadioButton6.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton6.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L1+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        else if((jRadioButton6.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        else if((jRadioButton6.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton5.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONEWAY");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
        else if((jRadioButton6.isSelected())&&(jRadioButton9.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        //------------------------------------------------------------------------------------------------
        
       else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
       else if((jRadioButton3.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton5.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        else if((jRadioButton3.isSelected())&&(jRadioButton7.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
         else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton3.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
        else if((jRadioButton3.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("ONE");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
         //------------------------------------------------------------------------------------------------
        else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton1.isSelected())&&(jRadioButton9.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton8.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
         else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton1.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
        else if((jRadioButton1.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L3)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L3);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L3+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONE");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
        //-------------------------------------------------------NEW LOACTION-----------------------------------------------------------------
        
        
       else if((jRadioButton6.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton6.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
       else if((jRadioButton6.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
       else if((jRadioButton6.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
       else if((jRadioButton6.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton5.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("ONEWAY");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
       else if((jRadioButton6.isSelected())&&(jRadioButton9.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("ECONOMY");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        //------------------------------------------------------------------------------------------------
        
       else if(jComboBox4.getSelectedItem().equals("AMSTERDAM AIRPORT SCHIPHOLI,NETHERLANDSY")&&(jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
      else if((jRadioButton3.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton5.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
       else if((jRadioButton3.isSelected())&&(jRadioButton7.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
        else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
       else if((jRadioButton3.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
       else if((jRadioButton3.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("FIRST CLASS");
            jTextField7.setText("ONE");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
         //------------------------------------------------------------------------------------------------
       else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("BUSINESS");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
       else if((jRadioButton1.isSelected())&&(jRadioButton9.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("BUSINESS");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
       else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton8.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("BUSINESS");
            jTextField7.setText("ONE-WAY");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("BUSINESS");
            jTextField7.setText("RETURN");
            jTextField6.setText("ONE");
            jTextField5.setText("NIL");        
                           
        }
       else if((jRadioButton1.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton7.isSelected()))
        {
            totalcost=(tax*(L4*2))/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("BUSINESS");
            jTextField7.setText("RETURN");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
       else if((jRadioButton1.isSelected())&&(jRadioButton8.isSelected())&&(jRadioButton9.isSelected()))
        {
            totalcost=(tax*L4)/100;
            String sTax =String.format("PKR %.2f", totalcost);
            jTextField1.setText(sTax);
            String subtotal =String.format("PKR %.2f",L4);
            jTextField3.setText(subtotal);
            String total =String.format("PKR %.2f",L4+totalcost);
            jTextField2.setText(total);
            jTextField14.setText(total);
            jTextField4.setText("BUSINESS");
            jTextField7.setText("ONE");
            jTextField6.setText("NIL");
            jTextField5.setText("ONE");        
                           
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        new PAGE1().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(international.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(international.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(international.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(international.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new international().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
